[apikey]
weather = "YOURS"
apihost = "YOURS.re.qweatherapi.com"  # 尚只接收和风天气 API

[secret]
token = "YOURS"

[server]
host = "0.0.0.0"
port = 9000
domain = ["https://manager.example.com", "http://localhost:5173"]  # 配置 CORS

[db]  # 目前，只支持 MySQL 及兼容 MySQL 的数据库
host = "YOURS"
port = 3306
user = "YOURS"
pass = "YOURS"  # 数据库密码
name = "YOURS"  # Database 名称

[log]
debug = false

[run]  # 目前，Golang 版本还不支持 WebSocket 连接，但预留本项配置，实际上恒为 true
serverless = true  # 是否使用 Serverless 模式，若为 true，则关闭 WebSocket 功能，适用于云函数的部署
