[apikey]
weather = "YOURS"
apihost = "YOURS.re.qweatherapi.com"  # 尚只接收和风天气 API

[secret]
token = "YOURS"

[server]
host = "0.0.0.0"
port = 8114
domain=["https://manager.example.com", "http://localhost:5173"]  # 配置 CORS

[log]
debug = false

[run]
serverless = true
